// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdkioJCr9lu1YGhV6XJC-T2en4bAmH80k',
    appId: '1:42180357468:web:9ee89f8fd2eebf7e362599',
    messagingSenderId: '42180357468',
    projectId: 'cash-canary',
    authDomain: 'cash-canary.firebaseapp.com',
    storageBucket: 'cash-canary.appspot.com',
    measurementId: 'G-1NE39M2VQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHqKHcsQS1WQRUxsYgaJSnnoocAxT7IA',
    appId: '1:42180357468:android:75f0795cef9e1696362599',
    messagingSenderId: '42180357468',
    projectId: 'cash-canary',
    storageBucket: 'cash-canary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllDlTqw8VsF7Tr9MFqM6PSNRNB46nUAk',
    appId: '1:42180357468:ios:5dd80a3ed49c7992362599',
    messagingSenderId: '42180357468',
    projectId: 'cash-canary',
    storageBucket: 'cash-canary.appspot.com',
    iosClientId: '42180357468-ne6jh974el1e9hurutmj7g7le762072f.apps.googleusercontent.com',
    iosBundleId: 'com.github.joshallen64',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDllDlTqw8VsF7Tr9MFqM6PSNRNB46nUAk',
    appId: '1:42180357468:ios:5dd80a3ed49c7992362599',
    messagingSenderId: '42180357468',
    projectId: 'cash-canary',
    storageBucket: 'cash-canary.appspot.com',
    iosClientId: '42180357468-ne6jh974el1e9hurutmj7g7le762072f.apps.googleusercontent.com',
    iosBundleId: 'com.github.joshallen64',
  );
}
